LSSTDESC/dataregistry

scripts/create_registry_db.py, scripts/register_cli.py, src/dataregistry/registrar.py
When registering a dataset can include the --dummy parameter. This will create an entry in the table but it wont read or copy any actual data (this is for testing purposes)
=> Add option for dummy entries

.github/workflows/documentation.yml
This CI will automatically build the documentation.
It will also publish the docs from the main branch to github pages for us. The built docs go into the "empty" `gh-pages` branch, which I've created.
=> Auto build/publish docs

src/dataregistry/query.py
I don't think there's any need for the commit to the database after the query execute, as nothing in the database is changing.
Is that correct?
=> Remove commit to database during query

.gitignore, src/dataregistry/query.py, tests/end_to_end_tests/test_query.py
When we do a query with `property_names=None` we were crashing, fixed this.
=> Fix bug where we have not specified any properties

scripts/create_registry_db.py, src/dataregistry/DataRegistry.py, src/dataregistry/db_basic.py, tests/unit_tests/test_connection.py
Fold the `create_db_engine` into the `DbConnection` class, and fix the tests to reflect that.
The function was a bit out of place, this tidies the code a little, keeping everything related to the connected within the `DbConnection` object.
=> Tidy db connection

src/cli/cli.py, src/cli/register.py, src/dataregistry/registrar.py, tests/end_to_end_tests/create_test_entries.py, tests/end_to_end_tests/test_query.py
Currently when registering a dataset with no execution, a default execution is made for the dataset.
Now you can modify the metadata of this default execution during dataset registration. So if you just have one dataset in an exectuion, this saves the user having to make an execution first, then assigning a dataset to it, it can all be done at dataset registration.
Executions with more than one dataset associated with them still need the execution to be made first.
=> Add ability to define execution name when registering a dataset

scripts/create_registry_db.py, src/dataregistry/registrar.py, src/dataregistry/registrar_util.py, tests/end_to_end_tests/create_test_entries.py, tests/unit_tests/test_registrar_util.py
Can now specify the path to a configuration file for the `access_API` when registering a dataset.
Also added come CI for the configuration file load function
=> Add `access_API_configuration` to `register_dataset`

docs/source/tutorial_notebooks/getting_started.ipynb, scripts/create_registry_db.py, src/dataregistry/DataRegistry.py, src/dataregistry/registrar.py, src/dataregistry/registrar_util.py, tests/unit_tests/test_rutil_copy_data.py
Overwriting directories requires deleting the previous directory to work.
In this branch
- Moved copying data to a function in registrar_util
- When copying a directory, it deletes it first if it exists
- Added a CI test for the copy_data function
=> Fix overwrite directories

scripts/create_registry_db.py, src/dataregistry/registrar/dataset.py, src/dataregistry/registrar/dataset_util.py, src/dataregistry/schema/schema.yaml, tests/end_to_end_tests/test_database.py, tests/unit_tests/test_dataset_status.py
Update the dataset table to include:
- status (-1: Invalid (e.g., copy data failed during creation), 1: Valid, 2: Archived, 3: deleted)
- archive_date (When archived)
- archive_path (Where archived to)
- delete_date (when deleted)
- delete_uid (who deleted)
- move_date (when last move)
Any more?
=> Add dataset status and move/delete/archive information

src/dataregistry/registrar/base_table_class.py, src/dataregistry/registrar/dataset.py, src/dataregistry/schema/schema.yaml, tests/end_to_end_tests/test_end_to_end.py
Can now delete datasets using `Registrar.dataset.delete(<dataset_id>)`.
Function :
- Checks the dataset exists, and that it is a "valid" (0 or 1) status
- Changes the status to `3` and sets the `delete_date` and `delete_uid` fields
- Deletes the data in the `root_dir`
Have added unit tests to make sure these things are happening
(Had to modify the `previous_dataset` function to be used also to search on `dataset_id` for this function to also use)
=> Add ability to delete datasets

src/dataregistry/registrar/dataset.py, src/dataregistry/registrar/registrar_util.py, tests/end_to_end_tests/test_end_to_end_python_api.py
Make fewer of the register dataset attributes (e.g., a description) mandatory.
Tidies the code a little. No functionality change.
=> Tidy python API CI test file

src/dataregistry/registrar/dataset.py, src/dataregistry/registrar/registrar_util.py, tests/end_to_end_tests/test_end_to_end_python_api.py
Decided we do not want to deal with how do auto-bump a dataset that has a suffix.
Therefore if the user tries to auto-bump a dataset with a suffix an error is raised.
A user can work with version suffixes and bumping manually, when registering the updated dataset they specify the version and suffix manually rather than trying to auto bump.
=> Raise error if dataset with version suffix gets auto bumped

src/dataregistry_cli/cli.py, src/dataregistry_cli/delete.py, src/dataregistry_cli/query.py, tests/end_to_end_tests/test_end_to_end_cli.py
Changes:
- Add ability to delete datasets using the CLI with `dregs delete dataset <dataset_id>`
- Added CI test in `test_end_to_end_cli.py` that creates a dataset using the CLI, then deletes it.
- Update `dregs ls` to also show the `dataset.status` field (might want to make showing delete datasets optional in the future)
=> Add ability to delete datasets with CLI

scripts/create_registry_db.py
Was accidentally overwriting the schema yaml file entries for the foreign keys.
Because we loop over the default and production schema, the entries were corrupt on the 2nd itteration.
=> Don't overwrite the schema_yaml dict entries during database creation

src/dataregistry/registrar/execution.py
When creating executions with input datasets from both the production and standard schema the `values` dict would have left over entries in the `input_id` of the `input_production_id` from the other schema.
The `input_production_id` for standard dependencies should be `None`, and vice versa for the production schema.
Now explicitly reset the non-used input ID in the `values` dict each time.
=> Input ID bug when creating executions 

.github/workflows/ci.yml, pyproject.toml
Updates Python CI default version to 3.10 (for pushes)
Also added Python 3.9 and 3.11 checks during pull requests
=> Update CI Python version to 3.10

docs/source/tutorial_notebooks/getting_started_1_register_datasets.ipynb, src/dataregistry/registrar/dataset.py, src/dataregistry/registrar/registrar_util.py, src/dataregistry/schema/schema.yaml, src/dataregistry_cli/cli.py, src/dataregistry_cli/register.py, tests/end_to_end_tests/database_test_utils.py, tests/end_to_end_tests/test_cli.py, tests/end_to_end_tests/test_database_functions.py, tests/end_to_end_tests/test_delete_dataset.py, tests/end_to_end_tests/test_keywords.py, tests/end_to_end_tests/test_modify.py, tests/end_to_end_tests/test_production_schema.py, tests/end_to_end_tests/test_register_dataset_alias.py, tests/end_to_end_tests/test_register_dataset_dummy.py, tests/end_to_end_tests/test_register_dataset_external.py, tests/end_to_end_tests/test_register_dataset_real_data.py, tests/end_to_end_tests/test_register_pipeline.py, tests/unit_tests/test_registrar_util.py
This supersedes the old pull request.
Replace `relative_path` with `name` as the mandatory quantity when registering datasets. Users can still specify a manual `relative_path` during registration if requested. If no `relative_path` is given, one is generated automatically from the name and version.
When overwriting datasets, users must provide the `name` and `relative_path` for the entry they wish to overwrite. 
- Update docs
=> Replace `relative_path` with `name` as the mandatory entry when registering datasets

docs/source/tutorial_notebooks/getting_started_1_register_datasets.ipynb, src/dataregistry/registrar/dataset.py, src/dataregistry_cli/cli.py, src/dataregistry_cli/register.py, tests/end_to_end_tests/database_test_utils.py, tests/end_to_end_tests/test_register_dataset_real_data.py
If a user tries to register a dataset via symbolic link, raise an error
=> Don't allow registering via symlinks

src/dataregistry/registrar/dataset.py
- Make sure `relative_path` is specified if `old_location` is None and the `location_type=dataregistry`
=> `old_location` checks

src/dataregistry/db_basic.py, src/dataregistry/registrar/dataset.py, tests/end_to_end_tests/test_database_functions.py, tests/end_to_end_tests/test_keywords.py
Make it so that `keywords` are always ingested into the `keyword` table in lower case, regardless of the user input. This prevents unwanted duplication of keywords through case differences.
Note that when querying, sqlalchemy+postgres is still case sensitive (both `=` and `==`), so when querying for keywords you still have to be case sensitive, in this case lower case. We could change the querying for keywords to remove case sensitivity also.
=> Keyword case sensitivity

src/dataregistry/query.py, tests/end_to_end_tests/test_query.py
Added a `get_all_tables()` function to `Query` class to return a set of the table names in the database.
Also updated `get_all_columns()` to be able to just return the column names from a chosen table, as well as the default behaviour of all tables.
=> `get_all_tables()`
